version: "3.8"
services:
  #バックエンド
  back:
    container_name: geek_back
    # for Apple Silicon Mac
    # platform: linux/arm64/v8
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/src
    ports:
      - 8080:80

  #ngrok(LINEbot ローカル動作確認用)
  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
      - ${NGROK_FRONT_PORT:-4040}:4040
    environment:
      NGROK_FRONT_PORT: front:3000
      NGROK_AUTH: ${NGROK_AUTH_TOKUN}
    # depends_on:
    #   - front
    networks:
      - default

volumes:
  node_modules_volume:
  build_volume:
